### ISSUE TITLE
懒得看了 自己来吧

### ISSUE THREAD

**Issue by JuneLeGency** [liaohuqiu/android-dynamic-load-awesome#3]
https://github.com/Qihoo360/DroidPlugin 

https://github.com/limpoxe/Android-Plugin-Framework

https://github.com/houkx/android-pluginmgr

https://github.com/bunnyblue/DroidFix

https://github.com/dodola/HotFix

https://github.com/jasonross/Nuwa

https://github.com/alibaba/AndFix

https://github.com/hongyangAndroid/AndroidChangeSkin

https://github.com/fengjundev/Android-Skin-Loader

**Comment by liaohuqiu** [comment]
Thank you.
